spring:
  datasource:
    url: jdbc:h2:mem:bookstore
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
logging:
  level:
    liquibase: info