spring:
  data:
    mongodb:
      database: bookstore
      host: localhost
      port: 27017
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - com.otus.bookstore.mongock.changelog
logging:
  level:
    liquibase: info